quarkus.http.port=8080

quarkus.smallrye-jwt.enabled=true
smallrye.jwt.sign.key.location=privateKey.pem

# Senhas para usuários mock de desenvolvimento
mock.user.admin.password=admin123
mock.user.client.password=cliente123

# Jacoco Test Coverage Configuration
quarkus.jacoco.report=true
quarkus.jacoco.minimum-line-coverage=0.5

# Expor as métricas do Prometheus publicamente
management.endpoints.web.exposure.include=prometheus

# Inclui o Swagger UI no build final para que esteja disponível
quarkus.swagger-ui.always-include=true